### ISSUE TITLE
How to debug 3D issues with icewm?

### ISSUE THREAD

**Issue by sriemer** [bbidulock/icewm#105]
We have a customer report that after updating from icewm 1.3.8 in SLED12-SP1 to icewm 1.3.12 in SLED12-SP2, 3D acceleration is not working at all any more. On GNOME 3 it works - same issue after fresh SLED12-SP2 installation. GPU is an NVIDIA Quadro M5000 with a single 1920x1080 monitor at DFP-0 and the proprietary nvidia driver.

The problem seems to be related to that high-end GPU as I can't reproduce this with a much cheaper NVIDIA Quadro GPU using the same driver.

Is there a way to enforce 3D acceleration on icewm?
How to debug the detection for 3D acceleration on icewm?

Thanks in advance!

**Comment by bbidulock** [comment]
I'm not aware of icewm doing anything with regard to 3D with the possible exception of the visuals that are used for window frames (which maybe should not be the default visual in some cases).  Nevertheless, I don't know that visual handling has changed really since 1.3.8 anyway.  Perhaps someone else can give you a hand.

**Comment by sriemer** [comment]
Thanks! This is rather about 3D applications not using 3D acceleration like `glxgears` not running at display frame rate only on IceWM. I'm closing this for now and try to get somehow more information from that customer.

**Comment by sriemer** [comment]
Found it: Customer tried to fool me. 3D is working and `glxgears` runs at display frame rate. The problem is located in his own application.
