### ISSUE TITLE
documentation format conversion?

### ISSUE THREAD

**Issue by gijsbers** [bbidulock/icewm#136]
What is the best way to move forward with the icewm documentation?
The SGML format is outdated and impopular. Makes it a bit of a hurdle to do anything with the doc/icewm.sgml file. How about if we convert it to something more modern and more accessible like MarkDown? Or something else?
This would also drop the dependency on sgml2html.

**Comment by bbidulock** [comment]
The problem is a bit greater: although the format is out of date, the content is also out of date.  sgml2html is only really a dependency for building from git.  When the package is built for release, it includes the converted documentation (last I checked).  I would prefer asciidoc to markdown, but any thing that generates the final html output is fine.

**Comment by gijsbers** [comment]
Replaced SGML with AsciiDoc. We can now plan how to improve content. How to remove the label "out of date"? What happened?

**Comment by gijsbers** [comment]
The man page has been made up-to-date. We'll stick with that for a while.
