### ISSUE TITLE
Ugly focus icon, alternative proposal

### ISSUE THREAD

**Issue by Code7R** [bbidulock/icewm#149]
Requesting for comments:

IMHO the focus icon added in recent changes is quite ugly. It's an XPM without alpha channel and the scaling makes it look really bad, see below.

I suggest another couple of icons (copyright: myself, license: whatever you want), see below.

Does anyone object if I add them?

Shall I drop the XPM version then?

And BTW, apparently the current loader prefers XPM version over PNG. Is this a bug or intentional? If former, shall I fix it in process?
![in-1 4 1](https://user-images.githubusercontent.com/10660264/28745084-b13a9b28-7470-11e7-99fa-c88ee7b23072.png)
![mine](https://user-images.githubusercontent.com/10660264/28745086-b6227606-7470-11e7-9616-b9be60b8a940.png)
![focus_16x16](https://user-images.githubusercontent.com/10660264/28745087-bd82ff06-7470-11e7-8c84-ca24ea3225f4.png)
![focus_32x32](https://user-images.githubusercontent.com/10660264/28745088-bd84348e-7470-11e7-8972-59a4b77642fb.png)

**Comment by gijsbers** [comment]
When was the focus icon added? 

An alpha channel may be good yes.

Taste is something personal and can lead to hurt feelings, but if I may speak up freely then your proposed icon is not that clear. The concept of focus may also be represented as something related to camera focus, or an arrow hitting the bullseye of a shooting target.
If we change the focus icon we may well opt for something fancy and attractive. There must be professionally looking icons out there which are not encumbered by troublesome licenses? 

Image format handling is also open to improvement. Some of the 1.4 work was a start in that direction. The problem with changing it is regressions, like we have seen. Suppose there exist both a focus.XPM and a focus.PNG. By favoring the .XPM we are more backwards compatible, not breaking old themes, not causing support issues.

**Comment by bbidulock** [comment]
Sure, remove the xpm and add the new png.

**Comment by ghost** [comment]
Could there be several alternatives used or usable? People could then select this or that; the size of these images should be quite small anyway and I think ... icewm-1.4.2.tar.xz here on my system has 1.2MB. I would not mind it being larger so it would be nice if users could select what they want to have or use. For example I have no real objection to keeping OR changing the focus picture but I'd rather like to choose on my own which variant to use either way, rather than someone else deciding onto me.

**Comment by gijsbers** [comment]
@shevegen One can create a ~/.icewm/icons directory and copy preferred icons to it. Icewm will then prefer those over the installed ones. There exist icon sets by users. [Here](http://sandbox.cz/~covex/icewm/iceicons/) is one example. We could start a collection or  a set of links if you help us :-)

**Comment by Code7R** [comment]
I don't know when exactly the focus icon was added. I have been abstinent from icewm hacking for many months now and when I checked recently... my god, it was full of stars^w icons :-).

What I meant with "preference of png" is that it currently prefers the .xpm file even when .png version is available in the same folder. IMHO this should be reversed - not because of the size (AFAICS every XPM file fits within a 4k sector) but because of the alpha channel. BTW, if you have png material as source, the result of scaling probably should look slightly better compared to XPM source.

Whether to switch completely to PNG or keep xpm for compat reasons, that can be discussed. At the moment, the file size is so little that it wouldn't matter if both versions are installed, IMHO. Even XPM versions are not that much bigger than PNG at this resolution.

WRT quality, no hard feelings here. Yes, I agree that it got a bit too blurry. I could try to fix it if someone asks me to.

**Comment by gijsbers** [comment]
:-)  Git log says focus xpm is from Mar 5 commit 198e0b.

The icon should also work fine on black themes like VitaBlack and UltraBlack-Blue. The current focus icon does that perfectly because of the white shading.
It would be nice if the lines are separated from the circle segments like this:
![f3](https://user-images.githubusercontent.com/4169687/28793147-5eb58cbe-7632-11e7-9172-1156d520df89.png)
and an alternative focus icon would be like the icon you see when focusing a camera like:
![f4](https://user-images.githubusercontent.com/4169687/28793189-7d243d4e-7632-11e7-9c10-d637dbb5909a.png)

Someone with a large HiDPI screen may wish to have large icon sizes?
Maybe use SVG format?

**Comment by bbidulock** [comment]
I like the first one.

**Comment by bbidulock** [comment]
There is a new focus icon and order changed from .xpm .png .svg to the other way around.  Are we done with this issue?

**Comment by Code7R** [comment]
It's fine, thank you.
