### ISSUE TITLE
icewm taskbutton toolbutoon are shrinked.

### ISSUE THREAD

**Issue by SolisX** [bbidulock/icewm#159]
Hello Everyone,

This taskbar is 30 pixmaps. I usually do 25 pixmaps so that may factor into the problem.
Taskbutton and toolbutton  is shrinking 1 line at the top and 1 line at the bottom. Also
The workspace button seems to be shrinking a few lines. Please look closely at the
screenshots. Postimage's white background makes it hard to see. You will need to download images and open them in an image viewer(FULLSCREEN) switch between the 2 screenshot to see what i'm talking about.

Bad Icewm-1.4.2.109
https://postimg.org/image/597781a0t/

Good Icewm-1.3.12
https://postimg.org/image/w6qxathwv/

This was tested with my icewm Dark-Ice theme found in the link below.
https://www.box-look.org/p/1175259/

**Comment by gijsbers** [comment]
Thanks for this report! If I understand you correctly the taskbar height is 30 pixels.

Could you perhaps toggle `PagerShowPreview` and see if that helps you?
It is known that PagerShowPreview has its peculiarities with respect to drawing.
For instance, it doesn't honor the workspace names. 
The question is to what extend it needs fixing or not.
I mean it is different. But does that mean it is worse?

The time format of your screendump has also changed. Was that on purpose?

BTW now that we're talking did you have a chance to play with icesound?
Would be interesting to hear your take on audio.
Also for the new icewmbg features.

**Comment by SolisX** [comment]
Hello Gijsbers,

I tried turning on and off PagerShowPreview but i still get shrinking toolbutton,taskbarminimized and taskbuttonbg.

As far as the time format i guess it's reading the time format for from /usr/share/icewm/
instead of my ~/.icewm location. My time format from my ~/.icewm  is 

TimeFormat=" %I:%M.%S%P"

I use  "space.xpm" for clock begin and use the "m.xpm" for clock end because the clock does not have a proper clock begin and clock end pixmaps. So themes look a bit funny if you don't use my time format. A good example would be my BT105 theme.

https://www.opendesktop.org/s/Window-Managers/p/1018169/

I will have to try icesound later. It's a bit late right now.

**Comment by gijsbers** [comment]
I examined taskbar/taskbuttonbg.xpm  taskbar/taskbuttonminimized.xpm  taskbar/toolbuttonbg.xpm from the Dark-Ice theme and compared them to your screendumps. This leads me to the conclusion that the 'Bad' screendump is actually rendered correctly, while the 'Good' screendump is actually incorrect. I can make this more clear with the following composited image:

![toolbutton3](https://user-images.githubusercontent.com/4169687/29580179-6acf4fae-8775-11e7-8d33-d0fc123aa544.png)

It shows on the left the pixmap for toolbuttonbg. In the middle the left part of 'Bad' shows a correct rendering of toolbuttonbg. The right 'Good' shows the incorrect rendering.
So no code needs to be fixed for this, which is good news as it shows the code is maturing.

I also understand why the `TimeFormat` is not correctly shown. There is a commit 140b82528ee609982652b7dad334be8ce72d885c from March 8 with comment

`Set the time format to '%T' for some locales when TaskBarClockLeds=1 and ledclock/colon.xpm is loaded.`

Which is already incorrect because it applies to all locales, not to "some". So, no matter what `TimeFormat` you specify,  if the theme has clock led pixmaps with at least a colon pixmap then you will always get '%T'. The default value for `TimeFormat` is '%X' when CONFIG_I18N is on, otherwise it is "%H:%M:%S". In my view the `TimeFormat` should only be changed if it hasn't been explicitly set in a preferences or theme file.

BTW the link to the wallpaper of BT105 is incorrect.
I have been enjoying your themes for quite a while now.
Thanks a lot for making them!

**Comment by SolisX** [comment]
Hello Gijsbers,

I'll see if i can correct the Dark-Ice theme. 

Also i made some corrections to the nano blu theme. Since you guys are now shipping icewm with it. I added the missing collapse,expand and ledclock xpms. I have attached the new nano blu theme below.

Move the nano zip file to the post below.

Glad to see you like my themes and your welcome.:)

Also forgot to mention with themes that use flat look when they are place on the top
it seems that the separators get shifted down 1 or 2 pixals. And when you click on
the collapse button it removes 1 pixal from the expand button.

**Comment by gijsbers** [comment]
Could you perhaps give me a concrete example of the flat look case?
Thanks a lot for your updated Nano Blue!

**Comment by SolisX** [comment]
Hello Gijsbers,

This is the problem with the flat look themes when placed at the top.
https://s29.postimg.org/yzo81gokn/taskbarbg.png

This is the way expand should look like.
https://s29.postimg.org/e57a5w4tj/collapse.png

Missing the black line.
https://s29.postimg.org/fo79om0rr/expand.png


Also i forgot the dot.xpm for the nano blu theme. I just added it. I will reupload here.
[Nano Blu-1.2.zip](https://github.com/bbidulock/icewm/files/1247461/Nano.Blu-1.2.zip)

**Comment by gijsbers** [comment]
Grazie,  è meglio di quello vecchio!

I checked the Flat look, but I fear we better leave this as is. If we change Flat then we need to verify all themes using it. Not someting I fancy. There are 9 different looks. A theme designer who chooses one should deal with its characteristics.

If we look closer at the collapse and expand buttons we see they are not exactly aligned:

![expandcollapse](https://user-images.githubusercontent.com/4169687/29686092-f682bb46-8917-11e7-8019-6b13c84172eb.png)

**Comment by SolisX** [comment]
Hello Gijsbers,

Ok. I aligned the collapse and expand buttons and still got the same results.

I made BT105 a long time ago i guess the link went bad i will see if i can find the new link.

BTW: Where is the documentation for icesound?

**Comment by gijsbers** [comment]
[doc for icesound](https://github.com/bbidulock/icewm/blob/icewm-1-4-BRANCH/doc/icesound.1.adoc)

**Comment by SolisX** [comment]
Hello gijsbers,

I tried icesound.  Problems.

1).windowClose.wav works but it does the sound when you refresh,cancel or create a document.
2).windowOpen.wav ? is this the same as launchAPP? not sure how to trigger this.
3).I tried startup.wav by adding icesound & to the startup script but i did not hear the startup.wav.
4).windowMin.wav is not working.

Tested with icewm-1.4.2.154.

**Comment by gijsbers** [comment]
Very helpful!
1. I fail to get this. How can I "refresh,cancel or create a document" like you do?
2. Could you start icesound with the --verbose option and look at its output? For example, when I hotkey (~/.icewm/keys) a new terminal then I get this.
3. It was obscured by other events. Now it has been given priority so it should now work.
But adding icesound to the startup script won't do any good since startup is running late.
Better let the new icewm-session start icesound for you or start it before icewm-session.
4. It was obscured by windowLower events. Should now work.

thx!

**Comment by SolisX** [comment]
Hello Gijsbers,

This two very small clips of windowsClose going off when canceling and resend information on
firefox.

https://www.sendspace.com/file/iliudc

https://www.sendspace.com/file/30ektm

**Comment by SolisX** [comment]
Hello Gijsbers,

Just tested icewm-1.4.2.171. It seems to be working better.

Notice when i change the theme 2 sounds are playing.

22:12:46.893: icesound: Received GUI event launchApp
22:12:46.893: icesound: Playing sample #4 (/home/owner/.icewm/sounds/launchApp.wav)
22:12:47.134: icesound: Received GUI event startup
22:12:47.134: icesound: Playing sample #0 (/home/owner/.icewm/sounds/startup.wav)

Also when i use startx i dont hear the startup.wav for icewm.

**Comment by gijsbers** [comment]
Dialogs are fixed, as you noticed, by adding support for Dialog open/close events.
As for the theme launchApp, you're right, but it's not clear how to improve it. If a menu is clicked you get this launchApp thing. Hm. Leaving that for now.

**Comment by SolisX** [comment]
Ok.

BTW: BT105 wallpaper link seems to work for me.

**Comment by gijsbers** [comment]
It does?? It gets me to a red planet while the wallpaper background shows a beautiful ancient tree.

**Comment by SolisX** [comment]
Hello Gijsbers,

Oh i see. The original background was red planet. I think i may have got the wallpaper from
nexus desktop wallpapers. Any ways you find it here.

https://s30.postimg.org/jc2qm5ez5/wallpaper.jpg
