### ISSUE TITLE
Logout command problem.

### ISSUE THREAD

**Issue by SolisX** [bbidulock/icewm#167]
Hello Everyone,

If i use "killall icewm" for the LogoutCommand the reboot and shutdown entries disappear from
the menu.

Tested on icewm-1.42.324.

**Comment by bbidulock** [comment]
LogoutCommand is run at the start of the logout process.  You are killing the window manager at the start of the logout process and will not see any further dialogs from it.  Understand?

**Comment by gijsbers** [comment]
Hm, should killing processes affect the contents of a menu?

It turns out the problem is different. When `LogoutCommand` is defined then `canShutdown()` in `wmdialog.cc` always returns **false**. Why should it? The reasoning might have been that if the _system_ preferences define a LogoutCommand then the user has logged in via a display manager and should be allowed to logout, but not to shutdown or reboot. But we now can assume the user owns his system and if a `ShutdownCommand` and `RebootCommand` are also defined then those menu entries should still be made available. If those menu entries are unwanted then keep their preferences empty.

At least this is a reasonable issue we should take seriously. The contents of the LogoutCommand don't actually matter. Give it an innocent value like "date" and the problem still occurs. Thanks for reporting this issue @SolisX ! :-)

**Comment by gijsbers** [comment]
@SolisX there is no reason to use killall in LogoutCommand. It can be left empty. If you really must logout via killing then use: `pkill -x -2 icewm`

**Comment by bbidulock** [comment]
The LogoutCommand has been defined that way since initial commit and I don't see a reason to change it here.  @SolisX was killing the window manager in the command, so it could not continue from there anyway.

**Comment by SolisX** [comment]
@bbidulock My problem was that the sub menus disappear if i set a command for logout. I did
not run the kill icewm or click on the logout button.

@gijsbers Ok thanks for the tip.

**Comment by bbidulock** [comment]
Be that as it may, the behavior is correct.

**Comment by SolisX** [comment]
@bbidulock Ok then i will closed this issue since that is the way it should work.
