### ISSUE TITLE
IDEA: Closing app with a middle click on taskbar

### ISSUE THREAD

**Issue by Code7R** [bbidulock/icewm#170]
Hello,

sometimes I would like to close a few windows while observing the taskbar the taskbar.
I would like to that without distraction, i.e. without having to focus the window and press Alt-F4 or use another context menu or similar things.

What comes to my mind is using the middle-click, a pattern you can see in some applications like Firefox's tabs.

So I found a good location to hook the button click and send a close action instead. A draft can be seen here, although i would massage it a bit before pushing to dev branch.

https://github.com/Code7R/icewm/commit/80497622a206d688f65e0d8fd383ad8f8c06d3cc

Is anyone saying VETO so far?

One thing I am struggling with is a safety mechanism I would like to a add. Something like holding a mod key (ctrl or alt) when doing the middle-click, so the window is not closed by mistake (or with assistance from retarded hardware like "modern" clickpads). And I cannot see the optimal way to store the state of a mod key yet. Wasted over an hour already but the event dispatching between yxapp.cc, ywindow.cc and others still looks like evil spaghetti design. But I am not an expert an on Xlib internals, unfortunately.

**Comment by mmogilvi** [comment]
My initial thought was "probably not", although after more thought I've revised that to "maybe / maybe not".  I was thinking of the taskbar right click menu that has "close" and several other window options, although you mention you don't like the menu option.

Safety mechanisms: Firefox has a robust safety mechanism for any form of accidental tab closure: The "Undo Close Tab" feature.  General windows and applications can not practically implement such a mechanism without defining more interfaces to be implemented in cooperation with many different applications.  On the other hand, I'm not sure I was even aware of middle-click-close feature, and don't recall ever accidentally closing a tab this way, even when pasting things (my most common use of middle click).

Concerning modifier keys, doesn't XButtonEvent have a "state" member that has modifier keys already tracked and set, according to https://www.x.org/archive/X11R7.5/doc/man/man3/XKeyEvent.3.html ?  I'm most familiar with Qt's QKeyEvent, although I suspect most GUI toolkits include something similar, because it is common to want clicks to do different things depending on modifier keys.

If a direct taskbar close window feature is included, how configurable should it be?  I'm not sure:

* Always available / unconfigurable?  It isn't clear how often a user might accidentally trigger it.
* Enable/disable it?  This is seems like an excessively special case for a configuration option.
* Actually be able to configure a general mapping of various modifer-click combinations to any of a variety of actions (perhaps based on righ-click menu)? But part of the attractiveness of icewm is that it is fairly small and simple, but a mapping mechanism seems like adding a significant amount of complexity.  Also, are there other actions that someone might actually want a shortcut for accessing that aren't already supported?

**Comment by bbidulock** [comment]
A boolean option that turns it on or off that initially defaults to off should suffice, no?

**Comment by gijsbers** [comment]
You can already do this with:
right button click + C

**Comment by gijsbers** [comment]
works even better than expected if one keeps the C pressed down and then right-click on the tasks that need to be killed.

**Comment by Code7R** [comment]
Well, partly. When you hold the hotkey button, your keypress is still sent to the application (depending on the focus model).
I still consider pressing the modkey to be the better solution. Will check that as soon as I find time - but the automated NIC management is more important ATM.

**Comment by Code7R** [comment]
Current version in git does the job, thanks @gijsbers !
