### ISSUE TITLE
Workspace configuration not effective, possible memory corruption

### ISSUE THREAD

**Issue by Code7R** [bbidulock/icewm#171]
I tried to configure something like:
WorkspaceNames="A", "B" , " 3 "

But it doesn't work. I get three workspace icons instead with the names 1, 2, 3.

While looking around, I saw that valgrind reports invalid memory reads all over the place, starting in (and probably caused by) workspace initialization. 

I also tried this:
WorkspaceNames="1", "2" # , " 3 ", " 4 "
which also showed valgrind errors, and the eye-catcher was workspaceCount set to four but I couldn't see how that would happen. Whatever it is, it looks strange.

==25970== Invalid read of size 1
==25970==    at 0x71E4520: __strcmp_sse2_unaligned (strcmp-sse2-unaligned.S:24)
==25970==    by 0x48D493: YWindowManager::readDesktopNames() (wmmgr.cc:2680)
==25970==    by 0x48CEE0: YWindowManager::initWorkspaces() (wmmgr.cc:2320)
==25970==    by 0x495A2C: YWMApp::YWMApp(int*, char***, char const*) (wmapp.cc:1238)
==25970==    by 0x4997C6: main (wmapp.cc:1703)
==25970==  Address 0xa773fe0 is 0 bytes inside a block of size 4 free'd
==25970==    at 0x4C2D81B: operator delete[](void*) (vg_replace_malloc.c:621)
==25970==    by 0x4597CC: addWorkspace(char const*, char const*, bool) (wmconfig.cc:57)
==25970==    by 0x435335: setOption(cfoption*, char*, char const*, bool, char*) (yconfig.cc:164)
==25970==    by 0x434A32: parseOption(cfoption*, char*) (yconfig.cc:259)
==25970==    by 0x434726: YConfig::parseConfiguration(cfoption*, char*) (yconfig.cc:280)
==25970==    by 0x434BC3: YConfig::loadConfigFile(cfoption*, upath) (yconfig.cc:287)
==25970==    by 0x434DB8: YConfig::findLoadConfigFile(IApp*, cfoption*, upath) (yconfig.cc:306)
==25970==    by 0x4599CF: WMConfig::loadConfiguration(IApp*, char const*) (wmconfig.cc:32)
==25970==    by 0x494BAD: YWMApp::YWMApp(int*, char***, char const*) (wmapp.cc:1088)
==25970==    by 0x4997C6: main (wmapp.cc:1703)
==25970==  Block was alloc'd at
==25970==    at 0x4C2C97F: operator new[](unsigned long) (vg_replace_malloc.c:423)
==25970==    by 0x42D6BC: newstr(char const*, int) (misc.cc:492)
==25970==    by 0x42D647: newstr(char const*) (misc.cc:482)
==25970==    by 0x45986F: addWorkspace(char const*, char const*, bool) (wmconfig.cc:68)
==25970==    by 0x435335: setOption(cfoption*, char*, char const*, bool, char*) (yconfig.cc:164)
==25970==    by 0x434A32: parseOption(cfoption*, char*) (yconfig.cc:259)
==25970==    by 0x434726: YConfig::parseConfiguration(cfoption*, char*) (yconfig.cc:280)
==25970==    by 0x434BC3: YConfig::loadConfigFile(cfoption*, upath) (yconfig.cc:287)
==25970==    by 0x434DB8: YConfig::findLoadConfigFile(IApp*, cfoption*, upath) (yconfig.cc:306)
==25970==    by 0x4599CF: WMConfig::loadConfiguration(IApp*, char const*) (wmconfig.cc:32)
==25970==    by 0x494AAF: YWMApp::YWMApp(int*, char***, char const*) (wmapp.cc:1072)
==25970==    by 0x4997C6: main (wmapp.cc:1703)

**Comment by bbidulock** [comment]
Last time I did a valgrind run, I fixed a lot of errors; however, there were a number of errors in the option parsing code that I just couldn't fix without rewriting it altogether.  The errors had to do more with minor memory leaks, so I just left them.  It looks like maybe string handling changes have turned those memory leaks into accessing freed memory, which is worse than a slight memory leak.  I have noticed that the stability and general behavior of the window manager has deteriorated with 1.4 releases in rather subtle ways: which is a little disconcerting as my original objective in forking was maintainability rather than feature enhancements.

In general the C++ code in IceWM is poor: more like C compiled with a C++ compiler, but not good C code either.  Functionality such as the focus model are strewn across so many methods, classes and files that it is quite difficult to understand how anything works at all.  I tried to restrict changes to a minimum if only because it breaks less.  I largely just applied bug fixes that were long outstanding and beefed up NetWM/EWMH compliance because it played poorly with current applications.  Getting focus on map behavior to follow EWMH has never worked right even yet.  I had some difficulties shoe-horning in addition, deletion and rename of desktops under the EWMH model.  IceWM never did name its workspaces, but I think that you will find that the _NET_DESKTOP_NAMES property properly follows the settings, so that external pagers work better.

Marko's accent on "feel" was a good one.  The window manager has traditionally had a good feel to it.  Without that, though, and if the feel is compromised, it will become just a poorly coded window manager.

For significant enhancements, I think that one's time would be better spent with openbox, pekwm, fluxbox or the like.  Blackbox (which I also forked for maintenance purposes) is another example of far better written C++ code, and I beefed the EWMH compliance for that one too.

I only started on IceWM because the USAF LPS distro was using it as the default desktop and I was considering using it for default WM on unexicon (my Arch Linux respin).  LPS has since dropped IceWM and moved to (if I remember correctly) openbox.  I moved on to ADWM, which I now use almost exclusively (my wife still runs blackbox, but then she was a metacity user before and couldn't handle a dynamic tiling window manager: she clicks, I keystroke).

Well, I'll stop rambling, but I think that enhancing IceWM always stands to compromise the feel that people like about the window manager.

**Comment by gijsbers** [comment]
Workspace names don't get drawn in PageShowPreview mode. Turn that off and it should work.

The comment sign may only work at the start of the line?

**Comment by gijsbers** [comment]
Tried to reproduce the valgrind output, but works fine for me.
That workspace name code is all committed Brian Bidulock    2013-10-09.

**Comment by Code7R** [comment]
Setting PagerShowPreview to false displays, in fact, the expected workspace names. Thanks for the hint, easier to start digging now.

The memory corruption is apparently gone with bfb21a6f7ac2e23917088ce111ff2846aa321d1c , at least my valgrind is happy now even when built with --debug, thanks @bbidulock !

Regarding the other remarks: I agree, there is lot of face-palming in icewm code and often you need to go really deep to understand why a certain design decision was made. Sometimes it looks like some trade-off on compiler restrictions (*) or to work around the explicit avoiding of STL usage, which is sometimes ok but then again the wheel is sometimes reinvented not in the best/optimal/intuitive way.

(*) that said, maybe we should consider to get rid of some old habits... even the Debian Oldstable has gcc-4.9.2, i.e. practically full C++11 support. I don't say we have to unleash the beast but some features like range-for-loops and "auto" and lambdas can be really handy.

**Comment by Code7R** [comment]
Looks good, thanks @gijsbers !
