### ISSUE TITLE
Ability to rearrange tabs by dragging with mouse: put on left button just like browsers

### ISSUE THREAD

**Issue by jidanni** [bbidulock/icewm#172]
For years at the bottom of my screen there was
```
shell emacs root_shell
```
corresponding to the three windows I use.
But one day shell died and I restarted it.

That day I had to deal with
```
emacs root_shell shell
```
Hard to get used to that whole day long!

So it would be great, just like as one drag tabs to reorder them in
browsers, one could reorder them in icewm, without having to kill
programs or restart icewm.

**Comment by gijsbers** [comment]
@jidanni  It is starting to become a trend that users ask for features which are already implemented... ;-)
I assume you tried to do it, but it didn't work? This may be because you used the wrong mouse button? If you use the right (third) mouse button to drag a task then it should work. At least it works fine for me on the latest greatest and best ever 1.4.3 version as yet unsurpassed in correctness and usability... :-)
Okay, I admit this feature isn't anywhere documented yet. This indicates that more gems are waiting to be discovered.
Could you perhaps comment on how you as a user experience the implementation of this feature? Was the mouse button wrong? Should it be configurable? Does it always work?
Any feedback is greatly appreciated as usual.

**Comment by jidanni** [comment]
Ah! It works, thanks!
(But not as visually smooth as when doing the same action in browsers.)

And it is good that it is not yet documented,
as it gives you a chance to move it to the proper -- left -- mouse
button, as in how all browsers do it.

Just like you already have left click select a tab (window) just like browsers do.

By the way currently middle click does the same as left click... whereas
in browsers they do the opposite.

So middle click should kill a window... but maybe ask first... or just
too dangerous. So don't bind.

**Comment by Code7R** [comment]
Hello Dan, thanks for input!
The last part of your request is probably covered by #170 - please comment there if that's what you had in mind.

**Comment by jidanni** [comment]
@Code7R yes, but as I only close a window once a week, I'll let the pros decide how to implement it.

**Comment by gijsbers** [comment]
You can give it a try...
- Left  mouse instead of right.
- Visually smooth.
- Use Alt+Middle to close.

**Comment by jidanni** [comment]
@gijsbers Thanks. I'll try it when it hits Debian sid.
Do remember to document all these features. Thanks.

**Comment by gijsbers** [comment]
@jidanni Okay, it's documented. If you're happy with it will you remember to close this?
Maybe someone else could test the new features a bit?

**Comment by Code7R** [comment]
@jidanni 1.4.3 was supposed to go into Sid and this may take a while. But I was going go make another snapshot release for experimental, would you accept this?

**Comment by jidanni** [comment]
I should see it soon.
$ apt-cache policy icewm
icewm:
  Installed: 1.4.3+mod+20170901-1
  Candidate: 1.4.3+mod+20170901-1
  Version table:
 *** 1.4.3+mod+20170901-1 990
        990 http://free.nchc.org.tw/debian experimental/main amd64 Packages
        100 /var/lib/dpkg/status
     1.3.8+mod+20161220-1 500
        500 http://free.nchc.org.tw/debian unstable/main amd64 Packages
