### ISSUE TITLE
Cannot scroll menus with mouse.

### ISSUE THREAD

**Issue by bbidulock** [bbidulock/icewm#213]
Do not know when this started happening, but sub-menus that are longer than the screen height do not have scroll buttons anymore and so it is impossible to select items lower on the list with the pointer.  See attached screenshot.
![2017-12-29-021224_1280x800_scrot](https://user-images.githubusercontent.com/5490751/34433716-52bc61bc-ec3e-11e7-98dd-4a927f3d535c.png)

**Comment by Code7R** [comment]
I cannot remember having seen any scroll buttons ever. But scrolling with the mouse wheel usually works.

Except for too many entries (like 100), then I see really strange behavior here - menu appearing below the screen, jumping around when you try to scroll, keeps moving even after you stopped scrolling.

**Comment by bbidulock** [comment]
Should not rely on anything more than move and Button1.  Tempted to just replace with a GTK menu.

**Comment by gijsbers** [comment]
This may just be one of the side effects of the signed/unsigned width/height conversion.

**Comment by bbidulock** [comment]
How so?

**Comment by gijsbers** [comment]
The menus no longer work as they did when they are higher than the vertical screen size. This is due to underflow occurring in calculations for differences in sizes which used to produce a signed value which could be used as a position. Static menu popup with single clicks for large menus also no longer works anymore since the signed -> unsigned conversion of dimensions.
