### ISSUE TITLE
argb visual capability

### ISSUE THREAD

**Issue by gensenio** [bbidulock/icewm#25]
Hi,

I got the 1.3.9 version of icewm working under
gentoo linux

As far as I can understand, I might need an
_argb-visual capable_ window manager, whether I want
this window's edges to appear smooth:

I've been trying cairo-clock, and all that I can see is a
black background 

Kind Regards,

**Comment by bedna-KU** [comment]
Hi gensenio,
Give me link to screenshot.

**Comment by gensenio** [comment]
here is it!
![cairo-clock-icewm1](https://cloud.githubusercontent.com/assets/3276068/7817583/3718e62c-03d6-11e5-95ef-589210a60c44.jpeg)

**Comment by gensenio** [comment]
i'm using icewm + compton composing manager and, for example, if i run  cairo clock in sawish + compton or in kde, transparency is rendered correctly

**Comment by bbidulock** [comment]
Yes, IceWM does not check that the client window is using a 32-bit ARGB visual before reparenting the window, usually into a 24 bpp True Color visual; but, it is cairo-clock's fault: it is stupid.  It could set override redirect and stay as a top-level window and fully exploit the argb visual.  It would then not even need compton.  If nothing else, it could at least shape itself using the SHAPE extension.

Of all the lightweight window managers I use (or have written), half work with cairo-clock/compton and half don't.  For the same reason as IceWM.  One old one that works, surprisingly, is CTWM (also try FVWM), and others such as Fluxbox do work.  My adwm window manager does the transparency with cairo/compton, but compton itself frags out on the dynamic window management because it cannot conceive of a dynamic tiling reparenting window manager.

**Comment by gensenio** [comment]
there is no way to fix it in icewm? eve tint2  and docky have the same issue

**Comment by gensenio** [comment]
any news?

**Comment by bedna-KU** [comment]
Try Cairo compositor with Cairo widget, without Compton.
