### ISSUE TITLE
Update copyright

### ISSUE THREAD

**Issue by jidanni** [bbidulock/icewm#285]
```
$ icewm --version
IceWM 1.4.3.0~pre-20180809, Copyright 1997-2003 Marko Macek, 2001 Mathias Hasselmann.
```
Doesn't this need updating to "2018"?

**Comment by bbidulock** [comment]
My original intention was to make icewm maintainable, not to generate additional code under copyright.  The code is still primarily the original authors' work.  Other contributors may wish to add their copyright to the list, but I think that it is fine in its original form.

**Comment by jidanni** [comment]
Well all I know is it looks like we are running a decade old version
unless one decodes the version number.

So maybe say also
last update 2018
or something that mom and pop would understand.

**Comment by Code7R** [comment]
My 2 cents: I keep ignoring the warning from our quality checker about having non-machine-readable copyright file. We should keep https://dep-team.pages.debian.net/deps/dep5/ in mind when redesigning this - although it's just a bunch of recommendations IMHO.

**Comment by rubyFeedback** [comment]
I understand the initial intent and use case / explanation by  bbidulock ; and to not be "too closely" associated with
code. And of course people investing time in other projects and so forth, so developers may come and go - that's
fine.

Still, I believe that jidanni makes a point in regards to --version. Perhaps if the naming is an issue,
and people do not want to, or feel too closely attached, some more generic term could be used?

Something like "IceWM contributors" or so, past 2018; this is just a suggestion, perhaps there
are better names. That way the "burden" may not fall on any individual developer per se and
people could still be happy because they know that the project is maintained. (Actually, I was
not even aware of the github icewm for quite some time, so I did not even know that the project
was picked up again. I guess quite a few people may still think that sourceforge contains the
latest icewm code, for example.)

I think there are a few projects out there that sort of shorten it, and then, if necessary, list
individual authors in e. g. AUTHORS.md or elsewhere. There are also users or developers
who don't quite care about the whole copyright issue, and are fine to contribute to projects
without attribution, so perhaps an "umbrella" term may be helpful. I am not a lawyer though -
my primary line of thought here is to indicate to people that icewm is not totally inactive.

Actually gisjbers is hugely active right now, I can almost barely keep up to date with the
latest releases! (Just kidding, I use batch-compilation via ruby scripts anyway to update,
just pointing out the activity - I am sure people like that more than an inactive project.) ;)

**Comment by gijsbers** [comment]
Is this more about what it looks than what it is?
Would it give a significant judicial advantage?
The claim that the output is non-machine-readable for the Debian quality checker
is humorous of course, because a regular expression suffices to parse it.
It is all a bit vague. Maybe it would help if you could at least be more precise
and concrete in your proposals.
Why is it important that mom and pops would understand it? Hahaha...
That so many very old versions still linger is more of a pressing nature.
Distributions still shipping 1.3.8, 1.3.12 or 1.4.2? Come on please.
In 1.8.0 a handful of long-standing focus bugs, which I have found most annoying
for a very long time, were finally fixed!!! Congratulations to all icewm fans out there.
http://icewm.sourceforge.net nicely redirects to https://ice-wm.org
and on sourceforge.net/projects/icewm it is also clear where to go to.
Maybe rubyFeedback could help others by wrapping up an easy-to-use icewm updater?
What is your favorite characteristic icewm pref setting?

**Comment by jidanni** [comment]
Apparently there has been a commit that makes it now say 2012 as latest date. However I swear it is now 2020 the last time I looked at a newspaper 😃

**Comment by gijsbers** [comment]
Marko contributed code till 2012. There is no need to swear.

**Comment by jidanni** [comment]
Maybe add
`", and others, %d", current_year();`

**Comment by bedna-KU** [comment]
I would replace "and others" with "update"

**Comment by jidanni** [comment]
```
$ /usr/sbin/exim --version|head
Exim version 4.94 #2 built 24-Jul-2020 11:31:47
Copyright (c) University of Cambridge, 1995 - 2018
(c) The Exim Maintainers and contributors in ACKNOWLEDGMENTS file, 2007 - 2018
Berkeley DB: Berkeley DB 5.3.28: (September  9, 2013)…
```

**Comment by jidanni** [comment]
We [observe](https://github.com/bbidulock/icewm/issues/556#issuecomment-786356343) users thinking they are using 2012 versions.
