### ISSUE TITLE
Question regarding the numerous #if 1 preprocessor directives

### ISSUE THREAD

**Issue by DeltaResero** [bbidulock/icewm#3]
While I can understand having preprocessor directives "#if 0" or "#if 1" with an "#else" statement, I don't understand why there are so many "#if 1" alone.  Are these still relevant for disabling certain blocks of code for debugging because if not the removal of them would help clean up the code a little?

**Comment by bbidulock** [comment]
For forks, I usually try to resist making wide ranging asthetic or other non-functional changes to the code: it makes applying patches based on upstream difficult later.  Also, as LPS is a major user of IceWM, non-functional changes still require re-auditing the result.   Nevertheless, I forked this version for everyone to use because upstream maintainers appear to have abdicated, so leave this issue open and we will see if we get more supporters of removal.

**Comment by bbidulock** [comment]
No takers.

**Comment by gijsbers** [comment]
I would support removng the '#if 1' statements. There are 41 of them. Not a huge number.

There are many more '#ifdef/#ifndef LITE' statements. 138 of them. These do clutter the code more. Some of them only remove/add a last argument to a function call. This could be avoided by a #define like:
#define ARGNLITE(x)   , x
