### ISSUE TITLE
icewm 1.5.1: Graphical corruption between elements in taskbar

### ISSUE THREAD

**Issue by apocalyptech** [bbidulock/icewm#330]
Just upgraded to 1.5.1 yesterday, and I'm now getting graphical corruption in the taskbar, inbetween the various taskbar elements.  For instance, this is the "default" theme:

![default](https://user-images.githubusercontent.com/443343/51189903-a85fd000-18a6-11e9-8600-f4272f3678eb.png)

This seems to happen on basically all the themes; it's less obvious on the ones which use gradients more heavily, but I think it happens on those too.  I'm not sure what other software versions would be useful to know, but I'm running xorg-server 1.20.3, nVidia binary drivers 415.25.

**Comment by andreass83** [comment]
I built 1.5.1 for CentOS 7.5.1804 and I can confirm that the issue exists there as well (xorg-server: 1.19.5).

Steps to produce even more graphical corruption in the task bar: 
- Open an application, e.g. xterm 
- Set the WM layer of the application window  to "Above dock"
- Move the window over the task bar
- => visual artifacts appear

I took a look into the implementation of TaskBar::paint() in wmtaskbar.cc. It seems that the code does not fill the bottom edge of the area to be updated. Maybe because "r.height()-1" is used instead of "r.height()". The following change removed the visual artifacts but is probably not exhaustive as further occurrences of "r.height()-1" exist in this method:

`else {`
`         int y = taskBarAtTop ? 0 : 1;`
`-        g.fillRect(r.x(), y + r.y(), r.width(), r.height() - 1);`
`+        g.fillRect(r.x(), y + r.y(), r.width(), r.height());`

**Comment by gijsbers** [comment]
This only applies to themes which don't have a taskbar background pixmap file `taskbar/taskbarbg.xpm`.

**Comment by apocalyptech** [comment]
I'm extremely late to the "confirming the resolution of the issue I reported" party, sorry about that!  Anyway, yep, confirmed from me also that the current github (in `icewm-1-4-BRANCH`) fixes this for me.  Thanks for fixing this ages ago!
