### ISSUE TITLE
Release 1.6.5 does not have pregenerated configure.

### ISSUE THREAD

**Issue by ghost** [bbidulock/icewm#425]
Hi! I'm interested in creating a package for the distribution I use, however I noticed the latest dist tarball has no pregenerated configure, as opposed to the 1.4.2 release. Is this intentional? I would like to avoid an autotools dependency, ideally.

**Comment by ghost** [comment]
Additionally, this causes a gettext requirement for building the most modern release, which is something I'd ideally like to avoid.

**Comment by ghost** [comment]
The only release that carries a generated configure is 1.4.2 and below.

**Comment by Code7R** [comment]
Guess why I insisted on adding an alternative build system. Try cmake. See INSTALL.cmakebuild for more information.

**Comment by gijsbers** [comment]
I assume you didn't use the recommended tar file
https://github.com/ice-wm/icewm/releases/download/1.6.5/icewm-1.6.5.tar.lz

**Comment by ghost** [comment]
> I assume you didn't use the recommended tar file
> https://github.com/ice-wm/icewm/releases/download/1.6.5/icewm-1.6.5.tar.lz

I rose the issue here, as this is the distribution of icewm I intend to use.

**Comment by ghost** [comment]
Besides, that tar file uses lzip. Who uses lzip other than icewm?

**Comment by ghost** [comment]
> Guess why I insisted on adding an alternative build system. Try cmake. See INSTALL.cmakebuild for more information.

I was scared away from using cmake, as it was listed as experimental. I will try it.

**Comment by gijsbers** [comment]
The link I gave you is for the code from this repository.

["Who uses lzip?"](https://en.wikipedia.org/wiki/Lzip#Application)

**Comment by Code7R** [comment]
A few people for sure. lzip is actually the better xz.

**Comment by bbidulock** [comment]
@periish the last release that was posted on this repository was 1.4.2.  This is since after the 1.4.2 release the official icewm.org website went offline and Bert graciously started the ice-wm.org website linked to [ice-wm](https://github.com/ice-wm)  project on github.  While development is still performed on this repository, official releases are now performed in the [project repository](https://github.com/ice-wm/icewm/releases).  The releases use lzip compression and this is the fashion of the day (it is preferred to xzip for a number of reasons listed on the link that Bert cited).  I converted all of my repositories to use lz instead of xz about a year ago and many open source projects have done the same. `autoconf` has supported distribution in lzip format for some time now.  Nevertheless, it was a fair question.
