### ISSUE TITLE
IceWM & Firefox

### ISSUE THREAD

**Issue by jsbuchenberg** [bbidulock/icewm#449]
Dear all,

since two weeks, firefox doesn't run anymore on my Open Suse Tumbleweed.
The firefox-windows starts, but it ends with
* a black background
* following message in red:
                 <toolbarbutton id="UITourTooltipClose" class="close-icon"
--------------^

OpenSuse Tumbleweed
Mozilla Firefox 78.0.2

I am just an user, so please apologize, when important information is missing.

Best regards

JS

**Comment by gijsbers** [comment]
You say it is since two weeks.
According to https://build.opensuse.org/package/show/openSUSE:Factory/MozillaFirefox
your firefox was upgraded 14 days ago.
While https://build.opensuse.org/package/show/openSUSE:Factory/icewm
shows that your icewm was last updated two months ago.
If there was a problem with your icewm, it should therefore
have showed up much sooner than 14 days ago.
The problem you describe also indicates it is a problem of firefox.
IceWM just places the window somewhere on the screen.
Then it is between firefox and the X11 server to get any content on it.
IceWM doesn't interfere with that. It couldn't.
