### ISSUE TITLE
Black on black closer in Google Earth Pro

### ISSUE THREAD

**Issue by jidanni** [bbidulock/icewm#462]
In Google Earth Pro, click on a photo.
![e](https://user-images.githubusercontent.com/1230959/89667302-7d1c5600-d90e-11ea-9d35-4102277b4f90.jpg)

You will notice there is no way to see the X in the upper right corner that is supposed to close the photo we just opened.
If you move the mouse over where it is, the pointer will change into a finger (Ah! we found it!)
But we can't see the X due to black on black. I made a red circle in the photo above to indicate the trouble area.

**Comment by gijsbers** [comment]
I tested this for you and found that the photo window is just one window without window manager decorations.
This bug can't be ascribed to IceWM. A window manager only places a window on the screen.
Once the window is visible, it is up to the application, in this case GEP, to draw to it.
IceWM cannot interfere with that. It is not possible for IceWM to influence
whether something inside the window is black or white or whatever.

I have tested this also on the FVWM2 window manager:

![gep-fvwm2](https://user-images.githubusercontent.com/4169687/89674835-19cbfd00-d8e9-11ea-92af-c7a490024de0.png)

And I have tested this on the Enlightenment window manager:

![gep-enlightenment](https://user-images.githubusercontent.com/4169687/89674873-29e3dc80-d8e9-11ea-917a-748ac9aa7e2a.png)

You see the same problem occurs there too.

When I observe the event communication of Google Earth Pro then I see that it does more strange things.
Like very weird configure requests that are most likely unintended and the result of not understanding the ICCCM specification. 

According to https://support.google.com/earth/thread/3541018?hl=en
they don't want to properly support their Linux version and if something weird
is going on then it must be the window manager, because they tested on Debian
and then it looked good, etc. Well, they did mess up here and there.

**Comment by jidanni** [comment]
OK I notified them at https://support.google.com/earth/thread/63657958 . Thanks.

**Comment by gijsbers** [comment]
The window with the photo is actually a 32-bit deep window, as opposed to the rest of the GEP windows, which are all 24-bits deep. If you run a compositor like compton or picom, then you see the black bar become transparent and the white window below it will shine through. The cross to close the window will then show itself. You can see that the photo is a separate window here:
![f](https://user-images.githubusercontent.com/4169687/90040264-085b6a00-dcc8-11ea-9416-267504672966.png)
The black bar you currently see is actually transparent. You can drag the photo with Alt + left mouse button to experiment. It is remarkable that they assume the presence of a compositor for translucency, but don't mention this in their requirements or on their support site.

**Comment by jidanni** [comment]
That's great research. Maybe you will have better luck than me getting a word in edgewise to them. Thanks.

**Comment by jidanni** [comment]
I was just thinking since you could solved #451 maybe you could solve this bug too.
As far as getting a word in edgewise to Google... well we don't have any family members that work there.
So maybe some hack variable could be added to icewm.

**Comment by gijsbers** [comment]
As mentioned above, you only need to run a compositor, like picom or compton.
Run it from your [startup](https://ice-wm.org/man/icewm-startup) file.
Then you can close this issue. It is unrelated to icewm.

**Comment by jidanni** [comment]
OK. P. S., [Compton is now picom](https://forum.mxlinux.org/viewtopic.php?t=55026).
