### ISSUE TITLE
ButtonFontNameXft up scales or down scales xpms.

### ISSUE THREAD

**Issue by JC7897** [bbidulock/icewm#467]
Hello everyone,

NormalButtonFontNameXft and ActiveButtonFontNameXft up scales or down scales buttonA.xpm, buttonI.xpm, workspacebuttonbg.xpm and workspacebuttonactive.xpm.

Here is the dialog box with the button font size at 8.
![dialog8](https://user-images.githubusercontent.com/65046150/89984242-6b470400-dcbc-11ea-8b44-b8549afe44ec.png)

Here is the dialog box with the button font size at 16.
![dialog16](https://user-images.githubusercontent.com/65046150/89984303-83b71e80-dcbc-11ea-8f8b-cadc384d3048.png)

This is a problem when trying to get the font smaller then the buttonA.xpm, buttonI.xpm, workspacebuttonbg.xpm and workspacesbuttonactive.xpm. Wouldn't it be better to make just have the fonts bleed over if you set the size to big instead of the font size increasing or decreasing the xpm size?

**Comment by gijsbers** [comment]
Good question. Consider two cases:

1. Some users have displays with very high resolution. They need to set large font sizes for readability.
2. Some users are visually impaired. They may need large or very large fonts to read anything.

So it would be really great if we could have themes to help these people.
Then buttons and dialogs and titlebars need to scale up to accommodate the larger fonts.
To bleed over the text outside of the button is not possible, because the button is a window
and anything written inside the window cannot be visible outside of it.
If the buttons would not scale then the upper and lower part of the text would be invisible.

**Comment by Code7R** [comment]
What you actually want is a "padding" setting, which guarantees you a certain amount of space between font and borders.
My question is, should it be absolute (pixels) or relative (percents of font size)?

**Comment by JC7897** [comment]
Well you guys have a better idea of what is need than i do so i will defer to you guys. I will try to adjust my themes to which ever you decide.

**Comment by Code7R** [comment]
@JC7897 Why shall we know better? Your report is just confusing. You say: "This is a problem when trying to get the font smaller then the buttonA.xpm, buttonI.xpm, workspacebuttonbg.xpm and workspacesbuttonactive.xpm". But WHY is that a problem?
"Wouldn't it be better to make just have the fonts bleed over if you set the size to big instead of the font size increasing or decreasing the xpm size?"
Bleeding over means?? Crossing the borders of the button pixmaps, not scale the buttons at all? So, eventually you would have a small button which is covered by a string which is much larger? Then people would ask what this UI bug doing there behind the font.
It simply does not make sense. Please explain or demonstrate what exactly you did imagine, and what are the specific details to make it look right (like mentioned "padding" setting, this is a simple concept from CSS, is this suitable or not? https://www.w3schools.com/css/css_padding.asp ).

**Comment by JC7897** [comment]
@Code7R Your report is just confusing.

Look at the title it's nice and centered.
![good](https://user-images.githubusercontent.com/65046150/90319531-933a9f80-df28-11ea-9161-da7fa137c277.png)

This is what i mean by bleed over.
![Bloodover](https://user-images.githubusercontent.com/65046150/90319549-bcf3c680-df28-11ea-8589-5ed6196311a5.png)

If you look at the buttonA.xpm at the top post, you will see  that the font controls the size of the buttonA.xpm not the actual size of the buttonA.xpm.  So the font is always as big as the button even if you change the font size. The font can not be made smaller than the button or bigger than the button.

**Comment by JC7897** [comment]
This is working for the dialog box but the workspace buttons are stretched.

![workspacebuttonstrecthed](https://user-images.githubusercontent.com/65046150/90347744-81b2de00-e075-11ea-8e65-be08e58e7989.png)

**Comment by JC7897** [comment]
This is working but the workspace buttons are not getting the proper size from the workspacebutton xpm. 

![workspace](https://user-images.githubusercontent.com/65046150/90538173-8684a880-e1c1-11ea-86cc-14d621544820.png)

**Comment by gijsbers** [comment]
It is not clear from your description what the problem is. Why doesn't it look good? I did find one possible improvement.

**Comment by JC7897** [comment]
The problem is that the workspace button size is not being set by the workspacebuttonbg.xpm or workspacebuttonactive.xpm. If you look at the screen shot the workspace button looks like it's 19x26 but my workspacebuttons are  24x26 so the button is shrinking for some reason.

**Comment by gijsbers** [comment]
Is the button shrinked or cut off?
Which version did work like you want?
Look at the theme jack from https://www.box-look.org/p/1018082/.
It has workspacebuttons 28 pixels wide, but the image shows them much smaller.
That seems normal to me.

**Comment by JC7897** [comment]
To me it looks shrinked. I think what i was is that when the workspacebuttons were controlled by fonts there was a bit more spacing.  Anyways, if it looks fine to you than i will just suck it to a difference of opinion.  Thanks.

**Comment by gijsbers** [comment]
@JC7897 If you say that it looks shrinked, then to what do you compare it?
Is there a previous version on which it didn't look shrinked?

My understanding of the source code is as follows.
There are two cases to discern:

1. PagerShowPreview=1. Then the width of a workspace button is determined by the ratio of the screen width to the screen height.
2. PagerShowPreview=0. Then the width of a workspace button is determined either by the workspace icon in the ~/.icewm/workspace/ directory if it exists, or else by the width of the workspace name when drawn by the workspace button font.

For the theme designer this means that the size of the workspacebutton XPM is not so influential. It just needs to accommodate the above two cases. That is, test a theme when PagerShowPreview=1 and when PagerShowPreview=0.

**Comment by JC7897** [comment]
Here is what the worskpacebuttons use to look like before on
https://github.com/bbidulock/icewm/commit/73fb8c11deac6db3832c26330fcd4de6ee3dc09f

![workspacebutton-old](https://user-images.githubusercontent.com/65046150/90760954-fdd34d00-e325-11ea-977e-aa8eca3576db.png)

Here is what the workspacebuttons look like now.
![workspace](https://user-images.githubusercontent.com/65046150/90761009-13e10d80-e326-11ea-8466-e39e70c0c0c0.png)
