### ISSUE TITLE
Editable strings in the preferences menu

### ISSUE THREAD

**Issue by Code7R** [bbidulock/icewm#473]
Idea:
Add a simple editor for various strings and numbers. In the preferences menu, when one clicks on the string values, the line editor starts. (This will recycle YInputLine class, just add a description text upfront).

(nevermind, the warning could be a bold string which gets added to the description text. Color flashing would be too childish here).

**Comment by gijsbers** [comment]
The preferences menu is a modal popup. Users have no way to interact with their applications once it is up, which is bad. It is therefore better to think about some other non-menu means.

**Comment by Code7R** [comment]
Ah, so putting inputline into menu won't work because modal? Okay, it was actually the second idea. The first one was amending AddressBar (probably subclass it) and show a name of the option on the right side. This would probably still work fine.

Regarding 75521f9112c55523b7bf0875c17048d964a0e1a1 - probably a useful thing but I cannot see it work, i.e. there is no change in the CtrlAltDel dialog compared to a couple of days ago.

(the uniform button rendering now is nice, by the way, thanks!)

**Comment by gijsbers** [comment]
It won't work because of modal, but we don't want it either because of HCI.
We won't reuse the AddressBar for preferences settings for several reasons.

Instead we can add new GUI elements, like for instance enriched YMsgBoxes.
We need to move the PrefsMenu from wmprog.cc to a new file wmpref.cc.
Then for every non-boolean (string or key) entry in the PrefsMenu we
can popup such a YMsgBox. The title is the name of the preference.
The label is the help text. The YInputLine receives the new value.
User clicks on OK or Cancel. Save it. Done.

There is no change in the CtrlAltDel dialog needed. It is unrelated.

**Comment by gijsbers** [comment]
Since version 2.2.0 and 2.2.1.
