### ISSUE TITLE
1.8.1 Autohide causing taskbar/toolbar to pop up all black

### ISSUE THREAD

**Issue by cheapy** [bbidulock/icewm#489]
This is on antiX 19.2 x64 totally stock, and up to date with IceWM 1.8.1 from testing repo (based on Debian SID).

If you could try it on your default setup to confirm whether the problem is with IceWM or downstream, please?

I tried it with double height turned on and off, and either way it went black.  Other users reported the problem initially and have asked me to bring it up here.  I'll keep testing with it turned off :)

Thanks
Bob C

**Comment by gijsbers** [comment]
In 1.8.0 the number of internal operations on state changes was reduced. This reduces the amount of work when a window appears or minimizes or focus is changed. This worked everywhere except here, because the taskbar used the wrong calls to become shown or hidden. Let me know if this works for you too.

**Comment by cheapy** [comment]
anticapitalista got this implemented as 1.8.2 on antiX 19  https://download.tuxfamily.org/antix/Testing/ , and we tested the permutations of autohide and double height with it.  It works well, now.

Thanks for your help.  I'll close the issue
