### ISSUE TITLE
return from fullscreen forgets original window size for xfce4-terminal and gnome-terminal in 1.8.x

### ISSUE THREAD

**Issue by celerini** [bbidulock/icewm#491]
After pressing F11 exactly 8 times (4x go to the fullscreen and back) the window size remains the same as in fullscreen. Another window then breaks even earlier. It broke my workflow so I returned to 1.7.0. Fedora 31 here, 1.8.2 koji build tested as well.

# 6th F11
06:58.389: 0x0600030: _WIN_LAYER(CARDINAL) = 4
06:58.389: 0x0600030: Visibility PartiallyObscured 
06:58.389: 0x0600030: Configure 0x600030 722x434+0+0
06:58.389: 0x0600030: Visibility Unobscured 
06:58.389: 0x0600030: Configure 0x600030 722x434+3+21 Send
06:58.389: 0x0600030: _NET_FRAME_EXTENTS(CARDINAL) = 3, 3, 21, 3
# 7th F11
06:58.833: 0x0600030: _NET_WM_STATE = _NET_WM_STATE_FOCUSED, _NET_WM_STATE_FULLSCREEN
06:58.839: 0x0600030: _WIN_LAYER(CARDINAL) = 14
06:58.839: 0x0600030: Configure 0x600030 1600x1200+0+0
06:58.840: 0x0600030: Visibility PartiallyObscured 
06:58.840: 0x0600030: Visibility Unobscured 
06:58.840: 0x0600030: Configure 0x600030 1600x1200+0+0 Send
06:58.840: 0x0600030: _NET_FRAME_EXTENTS(CARDINAL) = 0, 0, 0, 0
06:58.840: 0x0600030: Focus Normal Inferior
06:58.840: 0x0600030: Defocus Normal Inferior
# 8th F11
06:59.212: 0x0600030: _NET_WM_STATE = _NET_WM_STATE_FOCUSED
06:59.227: 0x0600030: _WIN_LAYER(CARDINAL) = 4
06:59.228: 0x0600030: Visibility PartiallyObscured 
06:59.228: 0x0600030: Configure 0x600030 722x434+0+0
06:59.228: 0x0600030: Visibility Unobscured 
06:59.228: 0x0600030: Configure 0x600030 722x434+3+21 Send
06:59.228: 0x0600030: _NET_FRAME_EXTENTS(CARDINAL) = 3, 3, 21, 3
# the bug
06:59.228: 0x0600030: Configure 0x600030 1595x1190+0+0
06:59.228: 0x0600030: Visibility PartiallyObscured 
06:59.228: 0x0600030: Visibility Unobscured 
06:59.228: 0x0600030: Configure 0x600030 1595x1190+3+21 Send
06:59.228: 0x0600030: Configure 0x600030 1595x1190+3+21 Send

**Comment by gijsbers** [comment]
Initially I could only reproduce it with gnome-terminal, but not xfce4-terminal, if I keep F11 pressed.
Then I set Synchronize=1 in preferences to slow down icewm and it is easier. It may be a timing issue?
I tried other terminals like roxterm, urxvt, mlterm, sakura, guake, tilda, but they don't reproduce it for me.
Are there perhaps more applications which exhibit this behavior?

**Comment by celerini** [comment]
> Initially I could only reproduce it with gnome-terminal, but not xfce4-terminal, if I keep F11 pressed.

Actually I _tapped_ eight times. It is fully reproducible for me after IceWM restart.

> Then I set Synchronize=1 in preferences to slow down icewm and it is easier. It may be a timing issue?

I can reproduce it even with this command (launched in the terminal) and with various sleep values, so it looks pretty deterministicaly to me:

while true; do icesh -f fullscreen; sleep 1; icesh -f restore; sleep 1; done

> I tried other terminals like roxterm, urxvt, mlterm, sakura, guake, tilda, but they don't reproduce it for me.
> Are there perhaps more applications which exhibit this behavior?

mate-terminal (VTE as well)

Please correct me if I am wrong but I thought that the "Configure 0x600030 1595x1190+3+21 Send" is IceWM invention, isn't it?

**Comment by gijsbers** [comment]
* gnome-terminal : very easily reproducible
* xfce4-terminal : only reproducible for me if preference Synchronize=1
* roxterm : not without menubar, yes with menubar and if preference Synchronize=1

Current hypothesis: application must be a VTE terminal and have a GDK menubar.

The `icesh -f spy` will only give you a first impression.
It misses redirect requests which the X server sends directly to container subwindow.
To fully see what is going one has to run examine the logevent output.
Then you will see that icewm receives a request to make it fill the screen (almost).
Icewm only obeys this request it receives from the X11 server.
It is therefore not a bug in icewm, but a bug in GTK.
My guess is that the GTK becomes impatient about its fullscreen restore request
and then does a XConfigureWindow, which the X11 server intercepts
because of the resize redirect and then icewm executes this request.

The question is open how to approach this...
Should icewm implement a workaround specifically for VTE-GTK terminals?

Or should icewm reshuffle its internal workings to exhibit a different timing?
Is there a recommended order between the request, resizing, and setting the window properties?

You can also define a global key binding for the F11 key to toggle fullscreen.
Then the initiative for fullscreen is no longer with the terminal and the bug is avoided.

Or submit a bug with GTK and avoid VTE-GTK terminals until they fix their bug.

xfce4-terminal, if it reproduces the bug, may go into an endless loop of fullscreen / restored,
if one keeps the F11 key pressed for a few seconds.

**Comment by gijsbers** [comment]
This works much better for me. Can you test it?

**Comment by celerini** [comment]
> This works much better for me. Can you test it?

tested in Xephyr and it works like a charm

thank you very much for your effort, explanation and fixing the bug

**Comment by gijsbers** [comment]
Thanks for your testing. Just to be clear, however, I didn't fix the bug, because the bug is in GTK.
What I did was: when a request arrives to fullscreen, or to restore back from fullscreen,
previously icewm would first update the _NET_WM_STATE and then go about executing
the request and resizing and setting properties. Now this order is reversed.
Now icewm first does the resizing and then update properties and _NET_WM_STATE.
The GTK terminals grok this better. So one may think: what order of execution 
do window managers normally follow? Appears that GNOME window managers
actually use the old icewm behavior! The EWMH standard doesn't say anything about this.
Other window managers follow the new icewm behavior. It makes sense to me
to first execute the request and finally update the _NET_WM_STATE as a way
of confirmation that the request from the application has completed successfully.

**Comment by celerini** [comment]
> Now icewm first does the resizing and then update properties and _NET_WM_STATE.

Such order makes a sense to me too. Thanks for this change.
