### ISSUE TITLE
latest gdk-pixbuf release (2.42.0) has gdk-pixbuf-xlib removed

### ISSUE THREAD

**Issue by Polynomial-C** [bbidulock/icewm#513]
Hi,

I am the Gentoo package maintainer of icewm and got the following downstream bug report about this issue: https://bugs.gentoo.org/753890

With the release of gdk-pixbuf-2.42.0 upstream has removed gdk-pixbuf-xlib support:

Their [release announcement](https://gitlab.gnome.org/GNOME/gdk-pixbuf/-/tags/2.42.0) has the following to say:
> `Split the gdk-pixbuf-xlib library to a separate repository`

And they moved the splitted gdk-pixbuf-xlib code into an [archived repository](https://gitlab.gnome.org/Archive/gdk-pixbuf-xlib) which contains the following note in the [README.md](https://gitlab.gnome.org/Archive/gdk-pixbuf-xlib/-/blob/master/README.md) file: 
> `GdkPixbuf-Xlib contains the deprecated API for integrating GdkPixbuf with Xlib data types.`
> `This library was originally shipped by [GdkPixbuf][gdk-pixbuf], and has since been moved out of the original repository.`
> `No newly written code should ever use this library.`
> `If your existing code depends on gdk-pixbuf-xlib, then you're strongly encouraged to port away from it.`

Any chance icewm can be migrated away from gdk-pixbuf-xlib?

**Comment by gijsbers** [comment]
Well it could, I suppose. So we need to replace GdkPixbuf with some other library.
What would be a good option to pursue? It needs good image scaling,
conversion to XImage and SVG support would be nice too.

**Comment by Code7R** [comment]
There is imlib2 which is still maintained. icewm even did support imlib1 long time ago.

**Comment by gijsbers** [comment]
Imlib2 looks good, but it has no SVG support.

**Comment by mattst88** [comment]
@ebassi might be able to make a suggestion.

**Comment by ebassi** [comment]
You can keep using gdk-pixbuf-xlib forever, if you already are using it.

The code in gdk-pixbuf-xlib hasn't been touched in 10 years, and won't ever be touched again; the reason why it was split off of the main gdk-pixbuf repository was to drop the last dependency on a windowing system. Of course, newly written code should not be using Xlib types directly either, but if you already are, then you most likely know what you're doing.

If you want to draw anything on an Xlib Drawable, you should use Cairo; if you want to get the data from a Drawable into a pixel buffer, you can take get an XImage and unpack the pixels into any RGBA buffer. The amount of variations in X11 installations in 2020 is definitely smaller than it was 20 years ago, so it's unlikely you'll be hitting the fallback paths inside gdk-pixbuf-xlib *anyway*.

In any case, I just did a release off of the split repository: https://gitlab.gnome.org/Archive/gdk-pixbuf-xlib/-/releases/2.40.2

**Comment by gijsbers** [comment]
Thank you @ebassi. This issue started because users could no longer compile on Gentoo due to missing dependency on gdk-pixbuf-xlib. Now you say that we can keep using gdk-pixbuf-xlib. Does this mean that Gentoo will again carry that library? At least the statement "You're strongly encouraged to port away from it" feels contradictory. "Strongly encouraged"? That feels like push, push, push.... 

The code in IceWM which now depends on gdk-pixbuf-xlib was committed in January 2007. It has served us well.

**Comment by Polynomial-C** [comment]
Gentoo has fixed the issue meanwhie. (see [1](https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=2752ea859f10bfc0cd26793605d61592f642ee9b) and [2](https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=e1906d5114232710a4a4d4d201764137870f7197))
IMHO the question still remains whether icewm should depend on a deprecated lib or migrate to something else. What if some security issue will be found in gdk-pixbuf-xlib? Will upstream fix it and roll a new release? What if gdk-pixbuf-xlib fails to build with future compilers/build-systems? Will upstream fix it? If not distros will start to drop the lib for sure.

**Comment by ebassi** [comment]
> Now you say that we can keep using gdk-pixbuf-xlib. Does this mean that Gentoo will again carry that library?

I am not responsible for downstream packaging. I was planning to do a release of gdk-pixbuf-xlib alongside gdk-pixbuf 2.42 in time for GNOME 3.38, but I forgot, so I did a late release for both.

> At least the statement "You're strongly encouraged to port away from it" feels contradictory.

Let's be honest, here: people are strongly encouraged to port away from X _in general_. Of course, if you're writing an X11 window manager, you're probably not going to do that, anyway. Additionally, gdk-pixbuf-xlib is the least of your worries: the library is completely feature and API frozen, and has been for the past 10+ years.

The encouragement in the `README` is there mostly for people writing applications, and doing things like trying to draw pixel buffers on top of X surfaces; ideally, those people should have already switched to Cairo, or any other drawing API.

> The code in IceWM which now depends on gdk-pixbuf-xlib was committed in January 2007. It has served us well.

I can reasonably promise you that there won't be any changes in gdk-pixbuf-xlib that will ever break working code.

> What if some security issue will be found in gdk-pixbuf-xlib? Will upstream fix it and roll a new release? What if gdk-pixbuf-xlib fails to build with future compilers/build-systems? Will upstream fix it?

To answer those questions in order:

 1. it's **exceedingly** unlikely that security issues will be found inside code that hasn't seen _any_ change since 2010, and was written almost 20 years ago. Additionally, I am not going to go and look for security issues in the code base. Of course, stranger things have happened, so if somebody opens a security-related issue and provides a fix, I'd be happy to review it and merge it.
 1. I will do releases for security issues; see [the security disclosure policy for GNOME](https://security.gnome.org) for the process.
 1. Again, it's extremely unlikely that things will fail to build—but, again, if there are issues in the build and a merge request, I'll be happy to review any contribution.
 1. I don't plan to spend *any* development time on gdk-pixbuf-xlib. Reviewing contributions: sure. Releasing fixes: not a problem. Anything else: no, sorry. What I *can* do, is mentor or help out people who wish to become maintainers. I can even sponsor people to get a [GNOME development account](https://wiki.gnome.org/Infrastructure/NewAccounts), if they wish to take over the maintenance of the library.

**Comment by gijsbers** [comment]
I'm happy to see Gentoo carrying gdk-pixbuf-xlib again. Without it gdk-pixbuf becomes irrelevant for us.

I am amazed about statements like "strongly encouraged to port away from X".
There are so many good X applications out there. It can't be expected they will be ported to non-X.
Calling them deprecated... Which undemocratic government decides that?
Using weakly typed programming languages with dynamic memory can also be called deprecated.
You are strongly encouraged to only use and develop formally verified software.

"Strongly encouraged" is govspeak. A proper single word for this may sound too unfriendly.
So use a benign word like "encouraged" and totally alter its meaning by "strongly".
"Be encouraged, but please look at my biceps and think about what spinach may do to it"... ;-)
Cheers.

**Comment by Code7R** [comment]
I am staring at HEAD right now. There are deprecation warnings with latest librsvg thrown from calls of rsvg_handle_close . The hint there is:

> warning: ‘gboolean rsvg_handle_close(RsvgHandle*, GError**)’ is deprecated: Use 'rsvg_handle_read_stream_sync' instead [-Wdeprecated-declarations]
>    79 |             rsvg_handle_close(handle, &error);

This recommendation is probably taken from https://developer.gnome.org/rsvg/stable/RsvgHandle.html#rsvg-handle-close .
But I don't think that this makes much sense there, because there is probably no additional error which we might to track. And if I read https://developer.gnome.org/rsvg/stable/RsvgHandle.html#rsvg-handle-new correctly then calling this rsvg_handle_close is probably superfluous, since the handle is dereferenced immediately afterwards anyway. So if there is no reason, I suggest to remove that rsvg_handle_close call.

Also, I am wondering why those methods and custom file reading were used and not the simplier API: https://developer.gnome.org/rsvg/stable/RsvgHandle.html#rsvg-handle-new-from-file . I doubt there is any need to read image data from a pipe.

**Comment by gijsbers** [comment]
By using from_data we avoid loading whatever I/O libraries librsvg currently fancies.
The rsvg_handle_close was recommended for an older librsvg, so we can support
that version too if we just tell GCC to ignore the deprecated warning for librsvg.

**Comment by Polynomial-C** [comment]
Anything else needs to be done here? I am under the impression that this issue has already been resolved.

**Comment by gijsbers** [comment]
Since you opened it, you are always in a position to close it, if that looks appropriate to you.
So we added support for the Imlib2 graphics subsystem, as an alternative to gdk-pixbuf-xlib.
That seems to work, apart maybe from one or two quality issues.
Thanks a lot for bringing this to our attention. I'll close it now for you.
