### ISSUE TITLE
changed behaviour of FocusOnAppRaise / RequestFocusOnAppRaise

### ISSUE THREAD

**Issue by jiribohac** [bbidulock/icewm#547]
Hi,

since commit 78e05053 the behaviour of FocusOnAppRaise and RequestFocusOnAppRaise has changed.
For decades, I have been running xterm with the "pop on bell" option and icewm with FocusOnAppRaise=false, RequestFocusOnAppRaise=true. The result was that whenever something (e.g. irssi) beeped in my xterm, I would get a flashing notification in the taskbar, but the xterm was not raised. I could continue working in the current window and only seee to the notification later.
Since 78e05053 the behaviour has changed. The beep causes xterm to be raised above my current window. The keyboard focus stays in the current window.

Is this behaviour intended? Is there a set of config options to get the old behaviour back?
The patch description says:
    Fix for EWMH restack raise requests.
    Reflect layer changes in the ABOVE and BELOW flags in the EWMH _NET_WM_STATE property.
Not very specific, so I can't see what the real intention was. I'll be happy to try to come up with a fix if this change was not intentional.

Thanks!

**Comment by gijsbers** [comment]
Good question. Xterm sends these configure requests whenever it receives a  Control-G:
```
IceWM: window=0x2E0000D: real configureRequest serial=7002309 parent=0x89D028 StackMode=Above
```
Previously, icewm didn't raise if `StackMode=Above` if `focusOnAppRaise=0`, but set the urgent flag.
Now the application is raised anyway, just not focused, if StackMode=Above and sibling=None.
But why depend on icewm to convert a raise request into an urgent flag, if the app asks just to raise?
There are two ways an app can set the urgent flag, if that is what you want:
1. By setting the UrgencyHint flag in the WM_HINTS property.
2. By setting the _NET_WM_STATE_DEMANDS_ATTENTION flag in the _NET_WM_STATE property.

It seems that xterm can support this:
```
       bellIsUrgent (class BellIsUrgent)
               Specifies whether to set the Urgency hint for the window
               manager when making a bell sound.  The default is “false”.
```

You need to disable in xterm the:
```
       popOnBell (class PopOnBell)
               Specifies whether the window would be raised when Control-G is
               received.  The default is “false”.
```
because that indeed raises the xterm, per the request it sends to icewm.

**Comment by jiribohac** [comment]
Thanks for the details - you're correct, I agree the new behaviour is reasonable. I have basically relied on a bug for decades.
I did actually try bellIsUrgent in xterm before reporting this here. But it did not work for me. Now I dug deeper and found a bug in xterm. bellIsUrgent does not work if xterm's always_highlight flag is turned on (xterm then fails to properly track the focus and in turn does not set the urgent hint because it thinks it is always focused. I sent a patch to the xterm maintainer.

Thanks for your time, closing this issue.
