### ISSUE TITLE
Emacs too low on screen at startup

### ISSUE THREAD

**Issue by jidanni** [bbidulock/icewm#550]
Perhaps one day a [long standing problem](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=567083) could be solved:
emacs always starts too low on the screen:

![Ebad](https://user-images.githubusercontent.com/1230959/107164802-808eb800-69eb-11eb-9e0b-948295cda26a.jpg)

And needs to be manually dragged up:

![Egood](https://user-images.githubusercontent.com/1230959/107164813-88e6f300-69eb-11eb-9092-7250152b6e79.jpg)

$ xrdb /dev/null
$ xrdb -query|wc
      0       0       0
$ emacs -q # or -Q
Hmm there are 200 message long [threads](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=3643)...

**Comment by gijsbers** [comment]
It looks like this problem is due to Emacs+GTK. On startup Emacs asks icewm to become visible. Icewm honors this request, but then immediately Emacs asks to become larger vertically to accommodate an extra status bar.
It should have first created this extra status bar, before asking to become mapped. Then icewm could place it on screen completely visible. I think your problem is easily solved by adding this to your `winoptions` file:
```
emacs.geometry: +0+-30
```
If need be, you can also set this pref: `LimitPosition=0`.

**Comment by jidanni** [comment]
Those workarounds are great to know, but I want to get this problem finally solved for future generations.
So are there any more details you would like to add?
Or perhaps you could send your analysis directly to bug-gnu-emacs@gnu.org !

**Comment by gijsbers** [comment]
There is already more than sufficient analysis in the links you gave above.

So did the workaround work for you? I could make a more automatic solution,
but that would require testing and evaluation by users, before I could release it.

**Comment by rubyFeedback** [comment]
> It looks like this problem is due to Emacs+GTK.

I also have a strange problem in ruby-gtk3 applications.

https://i.imgur.com/SR1aIlR.png

In the event it can not be easily seen, at the bottom bar, on the right
hand side, I can close entries via the mouse, but the bottom bar does
not instantly re-calculate the size afterwards. This is different to the
behaviour of regular applications, so this may be because I wrote the
ruby-gtk3 applications incorrectly (for example, they crash on exit
rather than exit gracefully ... even then I found icewm's behaviour a
bit confusing, because that spacer where the old application was
open, is recalculated at a later time or when I focus on e. g. the
first tabs ... anyway, sorry for distracting the issue here, I have not
yet investigated this in a way so as to make it easily reproducible for
others. But I wanted to comment that gtk does indeed seem to be
a bit peculiar in general.)

**Comment by gijsbers** [comment]
Is this related to #548?

**Comment by jidanni** [comment]
[mistake removed]

Putting
```
LimitPosition=0
```
into .icewm/preferences and restarting icewm and then running emacs -Q also didn't help, no matter what xrdb had.

So how did I survive this bug for a decade without going nuts each day?

\$ grep fulls [.emacs](https://www.jidanni.org/comp/configuration/.emacs)
```
         (fullscreen . maximized)
```

**Comment by gijsbers** [comment]
No, please read carefully. It said: "add this to your winoptions file." The `winoptions` file is in the same directory as your `preferences` file. It is explained in the man page [icewm-winoptions](https://ice-wm.org/man/icewm-winoptions). Make sure it has at least this line:
```
emacs.geometry: +0+-30
```
and do `icesh winoptions` to make icewm reload the winoptions from that file. It should make a difference, for sure, if you do it correctly.

**Comment by jidanni** [comment]
Ah! OK, it turns out one needs
```
emacs.geometry: +0+0
```
If one uses that "30" solution, the header bar is chopped.

**Comment by gijsbers** [comment]
Commit 8b624a0 introduces an automatic solution for icewm:
whenever an application resizes itself outside of the work area
then icewm will reposition it slightly towards the center,
such that its border is aligned with the border of the work area.
The "work area" is the area of the desktop which excludes the taskbar.
People are welcome to test and evaluate this. Does this fit with
how you want to use your applications and how they behave?

**Comment by jidanni** [comment]
OK, I'll test it once it hits Debian sid, and if it works, I'll hunt down all related open bugs and close them. Thanks!

**Comment by zaza42** [comment]
Ohh, no! It got too hard!
I am the guy who WANTS the windows outside the work area partially.

I'm using chromium a bit offset to up and left, to get a bit larger visible area with command: `wmctrl -i -r 0x04600007 -e 3,-5,-16,1485,867` (0x04600007 is the window id of chromium)
Before this patch it worked for years:
![scrot-2021-02-12-15-47-39_325x65](https://user-images.githubusercontent.com/16356124/107783079-232b9b80-6d4a-11eb-904c-e0a1e8531da3.png)
But after this patch I can't set negative values:
![scrot-2021-02-12-15-47-07_381x80](https://user-images.githubusercontent.com/16356124/107783127-3179b780-6d4a-11eb-9679-65bdd972cb0d.png)

Manually dragging the window outside works (alt+f7 or alt+mouse), but I can't set it within scripts.

**Comment by gijsbers** [comment]
Very well. Please try again.

**Comment by zaza42** [comment]
> Very well. Please try again.

Thx, it fixed! 
Keep up the good work!
