### ISSUE TITLE
Problems with latest IceWm from here

### ISSUE THREAD

**Issue by frankzen** [bbidulock/icewm#571]
There seems to be some sort of bug with changing themes. I don't think the file "theme" is being rewritten when themes are changed so Ice ends up being very confused. Do you have to do a "Save Changes" after changing themes. I just realized I haven't been doing that as Ice always rewrote the "theme" file. I uninstalled my cloned version and installed the "official" Debian Bullseye version and it doesn't have that bug.  I also noticed that occasionally Ice doesn't load stuff into the tray, and that is associated with errors in  the  .xsession-errors file like invalid MIT-MAGIC-COOKIE-1. I don't know what's going on there but I do know there is some sort of problem with themes in IceWm.

**Comment by Code7R** [comment]
I don't see exactly the same here but something different. After a few starts within Xephyr, latest icewm suddenly fails to do that and reports:
./icewm -display :1
IceWM: Can't open display: isplay. X must be running and $DISPLAY set.

See the missing number and garbage instead? Smells like some format buffer corruption.

Edit: version 2.2.1 shows the same kind of behavior. Another strange thing: strace -f ... does not reveal anything matching "COOKIE" nor Xauth (any letter case) which you would typically see there.

It's getting even stranger. After a short break, it seems to work again, without me having changed anything significant. Since I had strace logs anyway, I compared them with the current flow, and it's inconclusive.

```
359888 openat(AT_FDCWD, "/home.user/.icewm/preferences", O_RDONLY) = 3
359888 fstat(3, {st_mode=S_IFREG|0600, st_size=36052, ...}) = 0
359888 read(3, "# icewm preferences(debian/1.6.4"..., 36052) = 36052
359888 close(3)                         = 0
359888 stat("/home.user/.icewm/theme", {st_mode=S_IFREG|0644, st_size=371, ...}) = 0
359888 openat(AT_FDCWD, "/home.user/.icewm/theme", O_RDONLY) = 3
359888 fstat(3, {st_mode=S_IFREG|0644, st_size=371, ...}) = 0
359888 read(3, "Theme=\"blueHeart/default.theme\"\n"..., 371) = 371
359888 close(3)                         = 0
359888 rt_sigprocmask(SIG_BLOCK, [HUP], [], 8) = 0
359888 rt_sigprocmask(SIG_BLOCK, [], [HUP], 8) = 0
359888 pipe([3, 4])                     = 0
359888 fcntl(4, F_SETFL, O_RDONLY|O_NONBLOCK) = 0
359888 fcntl(3, F_SETFD, FD_CLOEXEC)    = 0
359888 fcntl(4, F_SETFD, FD_CLOEXEC)    = 0
359888 socket(AF_UNIX, SOCK_STREAM|SOCK_CLOEXEC, 0) = 5
359888 connect(5, {sa_family=AF_UNIX, sun_path=@"/tmp/.X11-unix/X1"}, 20) = 0
359888 getpeername(5, {sa_family=AF_UNIX, sun_path=@"/tmp/.X11-unix/X1"}, [124->20]) = 0
```
The logs are almost identical until the socket... part comes. There it's missing in the failing run, it simply starts loading MO catalogs (to format the error message) instead of establishing the X11 connection.

**Comment by frankzen** [comment]
Latest version from cloning here (2.3.0.12) crashes immediately upon starting. Everything killed by signal 11.

**Comment by frankzen** [comment]
2.3.0.15 works fine. Thanks
