### ISSUE TITLE
switching between 2 fullscreen window via alt+grave

### ISSUE THREAD

**Issue by zaza42** [bbidulock/icewm#630]
I already found another small glitch in version 2.9.3.

I used to compare the quality of 2 videos by switching them in fullscreen mpv with alt+grave. This new version flashes the below windows+taskbar+more for a fraction of a second while changing focus.

https://user-images.githubusercontent.com/16356124/146863180-4d4c6548-2dcd-46aa-9b88-072ab7593641.mp4

Any older IceWM version doesn't have this glitch, e.g. with 2.9.2 it looks:

https://user-images.githubusercontent.com/16356124/146863315-591c699c-e07f-46e6-9714-83b791cf18cb.mp4

Sorry again for being the user with such stupid use cases. ;->

**Comment by Code7R** [comment]
Not sure why but my FF refuses to play those videos.

I was going to report another problem, maybe it's the same as yours (just guessing by the description, sorry for hijacking).
Mine is this: when a video window runs in fuillscreen (!!), like Firefox playing Youtube, pushing Alt-Tab actually HIDES the fullscreen window immediately. That's not useful, I would like to see the quickswitch window on top of the fulscreen window. First I though this is because the next (temp. focused) window is overlapping - but no, the issue even occurs when the other window is on a different monitor. So the video just disappears and you stare at some unrelated windows which happened to be there.

Actually, I started observing this behavior a while ago - I could bisect if requested. OTOH my gut feeling says that it could have started around the same time as #631.

**Comment by gijsbers** [comment]
As I said previously, the output of icesh spy on those windows
plus the root window can be much more insightful than video. 
My mpv seems to be missing useful codecs. How to get those?

**Comment by gijsbers** [comment]
It was a timing issue. I found a way to reduce the number of calls to XRestackWindows.
It should make icewm a little faster anyway. Could you give this a prolonged test?

**Comment by zaza42** [comment]
Ok, the latest git version has fixed it. 🖒
