### ISSUE TITLE
Icewm and plank issue

### ISSUE THREAD

**Issue by seraphim719** [bbidulock/icewm#653]
So I've installed icewm and plank the only issue is when I'm using a standalone compositor suck as picom the dock blocks mouse controls for about two inches of the screen if I add a shadow it's shows the box that's blocking me from grabbing the windows underneath it.

**Comment by gijsbers** [comment]
Can you add a screencast? Are you sure this is a icewm bug? Not a plank bug?

**Comment by seraphim719** [comment]
I've tried with Cairo dock as well and had the same result when using any compositor. from what I understand there's no placement for dockapps in icewm which only becomes an issue if your using a compositor like picom as well as a dock, I've found some referenced issues similar but making icedock work isn't an easy task since the repos are missing from Debian.

**Comment by gijsbers** [comment]
Which version of icewm do you run? Icewm supports [DockApps](https://www.dockapps.net/) since [2.4.0](https://github.com/ice-wm/icewm/releases/tag/2.4.0). Hence there is no reason to run icedock, which is unmaintained since 2006 anyway. When you run picom, the compositor makes the plank window invisible, but it is still there and blocks the icewm window grabs if your mouse is over it. The only way to circumvent that is to add a task dock to icewm natively.

**Comment by seraphim719** [comment]
I'm at 2.9 the dock runs but with compositor as you said any windows within two inches of the edge of the screen that the docks on have blocked mouse output I'm trying to get that screen space usable again.

**Comment by gijsbers** [comment]
This issue only arises with the `picom` external compositor, it seems. Hence `picom` makes some decisions that in the case of icewm are insufficient. For example, `picom` may have to take into account the fact that some WMs, like icewm and fluxbox, are designed to use an extra window nesting, called a `container`. See the output of `xwininfo -frame -tree`.
