### ISSUE TITLE
[Termux] Swapping file paths

### ISSUE THREAD

**Issue by IntinteDAO** [bbidulock/icewm#741]
I don't know how to write it, overall it's cool that IceWM will have direct support in Termux without patches.

On the other hand, it is about file paths. These are written absolutely (e.g. /usr/bin). Termux, on the other hand, runs on Android and it has its main directories in other places (e.g. /data/data/com.termux/files/usr/bin). As a result, menu generation does not work.

This is how I dealt with Termux (along with the help), however if you want to rework IceWM, you can take this into account and import / rework it to include Termux paths or in general somehow check all POSIX systems?

https://github.com/termux-user-repository/tur/commit/9d2c92aac609d05480a19b7f7c43a07e289df5d6

**Comment by gijsbers** [comment]
Thanks. The patch reduces the readability of the code and because at the moment the audience is tiny, I prefer not to include it. I also wonder if adding some `sed` commands to your build script could achieve the same effect. I have added this issue to the installation instructions section of the [Wiki](https://github.com/bbidulock/icewm/wiki), so it can be found by others.
