### ISSUE TITLE
Reboot/Shutdown button compatible with gnome-polkit.

### ISSUE THREAD

**Issue by yifanjiang** [bbidulock/icewm#80]
In a polkitd enabled system running icewm whose policy does not allow an ordinary user to reboot, when an ordinary user wants to reboot, a graphic password window is expected to be ready to authenticate.

I want to achieve this by running a polkit gnome agent. When I have a /usr/lib/polkit-gnome-authentication-agent-1 running in background. I tried things like following, and meet a weird problem:

```
$ nohup /usr/lib/polkit-gnome-authentication-agent-1 &
$ systemctl reboot # run from xterm 
```

=> The authentication dialog can be pop up successfully

=> However clicking the reboot button from the icewm "logout" submenu, the
     desktop looks "frozen" without accepting mouse and keyboard events.

Interestingly, it actually not hangs, wait for 10-20 minutes or so, the
authentication dialog pops out, which behaves in a very sluggish way. And
each of the subsequent mouse/keyboard actions become extremely slowly
responded.

Hanging around icewm src, I found the following attempted patch actually could 
resolve the problem. While the difference seems runCommand() ends up with calling "execvp()" 
and doLogout() ends up with calling "system()". 

But the thing is I am pretty new to icewm, and not very experienced of subtle practice of system() and 
execvp() running in the context. So I probably underestimated the risk of the change. Are there any one here could possibly help to take a look? Any thoughts will be appreciated. Thank you. If you think submitting the following patch is fine, I will do that :-)

```
Index: icewm-1.3.12/src/wmapp.cc
===================================================================
--- icewm-1.3.12.orig/src/wmapp.cc
+++ icewm-1.3.12/src/wmapp.cc
@@ -1821,7 +1821,7 @@ void YWMApp::handleSMAction(int message)
         break;
     case ICEWM_ACTION_REBOOT:
         rebootOrShutdown = 1;
-        wmapp->doLogout();
+       wmapp->runCommand(rebootCommand);
         break;
     case ICEWM_ACTION_RESTARTWM:
         wmapp->restartClient(0, 0);
```

**Comment by bbidulock** [comment]
It works from the xterm because you are in an interactive shell.  Commands executed by system() use /bin/sh -c "command", which is not interactive.
Now, systemd is foolish.  It has its own concept as to whether a graphical terminal is running.  Most applications just use the presence of the DISPLAY environment variable and the ability to open that display to distinguish graphical session verses console sessions.  systemd-logind thinks it knows better but doesn't.  If you start a graphical session with 'startx' on the console, systemd thinks it is still in a console session.  I reported this problems over a year ago, but it has not been fixed.  Only if you log in via a display manager does it think that you are in a graphical session.
That said, you do not need polkit nor admin privileges to reboot a systemd machine: you just can't use the 'systemctl' command.  The dbus interface to logind works just fine.  This is because the dbus interface knows where you are coming from (the local console or graphical seat).
So, the [xde-logout](/bbidulock/xde-session) works just fine and that is what I use.
